name: civilshots
description: "Empowering UPSC aspirants with a cutting-edge mobile experience where Flutter's elegance meets academic excellence"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  fpdart: ^1.1.1
  get_it: ^8.0.2
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.3.0
  supabase_flutter: ^2.8.1
  logger: ^2.5.0
  dotted_border: ^2.1.0
  image_picker: ^1.0.4
  uuid: ^4.5.1
  internet_connection_checker_plus: ^2.7.0
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.14
  path_provider: ^2.1.5
  flutter_markdown: ^0.7.6+2
  flutter_quill: ^11.0.0
  flutter_quill_extensions: ^11.0.0
  flutter_localizations:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  device_info_plus: ^11.3.0
  video_player: ^2.9.3
  video_player_android: ^2.7.17


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/images/
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
